# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Refresh version on go.dev
      if: ${{ github.event_name == 'pull_request' && github.ref_type == 'tag' }}
      run: GOPROXY=proxy.golang.org go list -m github.com/PlanitarInc/slc@${GITHUB_REF_NAME}
