# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race -covermode atomic -coverprofile=covprofile ./...

    - name: Refresh version on go.dev
      if: github.event_name == 'push' && github.ref_type == 'tag'
      env:
        GOPROXY: proxy.golang.org 
        PACKAGE_VERSION: ${{ github.ref_name }}
      run: go list -m github.com/PlanitarInc/slc@${PACKAGE_VERSION}

    - name: Send coverage to Coveralls.io
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go install github.com/mattn/goveralls@latest
        goveralls -coverprofile=covprofile -service=github
